### ISSUE TITLE
Please add 0.2.0 on crates.io

### ISSUE THREAD

**Issue by tjyang** [lebe-dev/zabbix-api-rs#5]
https://crates.io/crates/zabbix-api still showing 0.1.0

**Comment by lebe-dev** [comment]
Because 0.2.0 is not ready for release yet. I'm testing integration `zabbix-api` crate in my [wszl](https://github.com/tinyops-ru/zabbix-lld-ws) tool.

If you want to use dev version use can add it:

```toml
[dependencies]
zabbix-api = { git = "https://github.com/lebe-dev/zabbix-api-rs.git" }
```
